package main

import (
	"bytes"
	"text/template"
)

const templateBody = `
// {{ .Method }}
func (xs {{ .Slice }}) {{ .Method }}() []{{ .Type }} {
	sli := make([]{{ .Type }}, 0, len(xs))
	for i := range xs {
		sli = append(sli, xs[i].{{ .Field }})
	}
	return sli
}
`

// Replace variable from key to value in template.
type TemplateMapper struct {
	Slice  string
	Method string
	Type   string
	Field  string
}

func generate(data data) string {
	pkgName := data.pkgName
	sliceName := data.sliceName
	infos := data.infos
	var txt string

	// Append header
	txt += "// Code generated by go generate DO NOT EDIT.\n\n"
	txt += "package " + pkgName + "\n"

	// append templates
	var doc bytes.Buffer
	tp, err := template.New("").Parse(templateBody)
	if err != nil {
		panic(err)
	}
	for _, info := range infos {
		data := &TemplateMapper{
			Slice:  sliceName,
			Method: NewMethodName(info.Name),
			Type:   info.Type,
			Field:  info.Name,
		}

		err = tp.Execute(&doc, data)
		if err != nil {
			panic(err)
		}
	}
	txt += doc.String()
	return txt
}
